# Services: MySQL database, Prosody server and the PEAK's Directory Facilitator agent
services:
  server:
    container_name: prosody.peak
    image: unclev/prosody-docker-extended
    ports:
      - 5222:5222
      - 5281:5281
    volumes:
      - './server/config:/etc/prosody'
      - './server/data:/var/lib/prosody'
      - './server/log:/var/log/prosody'
      - './server/modules:/usr/lib/prosody/modules-community'
  df:
    container_name: df.peak
    depends_on:
      - server
    build: .
    ports: 
      - 10000:10000
networks:
  peak:
    external: true

